name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master   
    paths:
      - '**/*'  

jobs:
  build-and-deploy:
    runs-on: 'node20'
    
    steps:
      # 1. 리포지토리 체크아웃
      - name: Check out repository
        uses: actions/checkout@v2
        
      # 2. dist 폴더 생성
      - name: Create dist folder
        run: mkdir -p dist

      # 3. 모든 폴더에서 index.html 파일을 dist 폴더로 복사
      - name: Copy all index.html files to dist
        run: |
          find . -name 'index.html' -exec cp {} dist/ \;

      # 4. GitHub Pages에 배포 (GitHub Pages를 사용하는 경우)
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # gh-pages 브랜치에 배포
          folder: dist      # dist 폴더를 배포
          token: ${{ secrets.GITHUB_TOKEN }}  # GitHub에서 제공하는 기본 토큰
